Resources:
  TimeInfo:
    Type: Custom::TimeInfo
    Properties:
      ServiceToken: !GetAtt GetTimeInfo.Arn
      TimeZone: !Ref TimeZone

  GetTimeInfoRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "arn:aws:logs:*:*:*"

  GetTimeInfo:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GetTimeInfo
      Role: !GetAtt GetTimeInfoRole.Arn
      Runtime: python3.9
      Handler: cfn_lambda.lambda_handler
      Code:
        S3Bucket: nttdatacfpy
        S3Key: cfn_lambda.zip

Parameters:
  TimeZone:
    Description: Only the european city. As per http://worldtimeapi.org/api/timezone/Europe
    Type: String
    Default: London
    AllowedValues:
      - Amsterdam
      - Andorra
      - Astrakhan
      - Athens
      - Belgrade
      - Berlin
      - Brussels
      - Bucharest
      - Budapest
      - Chisinau
      - Copenhagen
      - Dublin
      - Gibraltar
      - Helsinki
      - Istanbul
      - Kaliningrad
      - Kiev
      - Kirov
      - Lisbon
      - London
      - Luxembourg
      - Madrid
      - Malta
      - Minsk
      - Monaco
      - Moscow
      - Oslo
      - Paris
      - Prague
      - Riga
      - Rome
      - Samara
      - Saratov
      - Simferopol
      - Sofia
      - Stockholm
      - Tallinn
      - Tirane
      - Ulyanovsk
      - Uzhgorod
      - Vienna
      - Vilnius
      - Volgograd
      - Warsaw
      - Zaporozhye
      - Zurich

Outputs:
  TimeInformation:
    Description: Time information of specified timezone
    Value: !GetAtt TimeInfo.timeInfo
  UnixTime:
    Description: UnixTime of specified timezone
    Value: !GetAtt TimeInfo.unixTime
